#!/bin/bash
#$Id: new_weather  01-21-2009 12:44PM wimac ver: 09.022.2007

# http://xoap.weather.com/weather/local/48126?cc=*&dayf=5&link=xoap&prod=xoap&par=1085093692&key=b9576afcdb69f9aa

wxurl='http://xoap.weather.com/weather/local/48126?cc=*&dayf=5&link=xoap&prod=xoap&par=1085093692&key=b9576afcdb69f9aa'

#wget -q -O-  $wxurl | \
#extract current conditions
#sed -n -e 's/.*<tmp>\(.*\)<\/tmp>.*/\1/p'
#sed -n -e 's/.*<t>\(.*\)<\/t>.*/\1/p' in.xml
for tag in tmp odst lsup

do
    grep  $tag in.xml | tr -d '\t' | sed 's/^<.*>\([^<].*\)<.*>$/\1/' | sed -n -e 's/.*<.*>\(.*\)<\/.*>.*/\1/p'

done
sed -i -n -e “/[myblock]/{
p
: loop
n
/[\/myblockt]/!b loop
}
p” $xmlfile
